const cards = [
    {
        id: 0,
        name: "John Smith",
        company: "ABC Company",
        title: "Amazing Results with Arik’s Premium Web Design Services.",
        desc: "Arik is a top-notch web designer who created a stunning website for my business. He was attentive to my needs and provided excellent customer service throughout the entire process. I highly recommend his services.",
        img: "john-smith.png",
        logo: "logo-small-01.svg",
    },
    {
        id: 1,
        name: "Karen Lee",
        company: "Redwood Technologies",
        title: "Professional, Collaborative Web Design Experience with Arik.",
        desc: "I had the pleasure of working with Arik on a website development project and was blown away by his expertise and professionalism. He made the process seamless and delivered a website that exceeded our expectations. I highly recommend Arik for all your web development needs.",
        img: "karen-lee.png",
        logo: "logo-small-03.svg",
    },
    {
        id: 2,
        name: "Emily Davis",
        company: "Greenway Industries",
        title: "Web Design and Content Solutions: Stand Out from the Crowd.",
        desc: "Arik's SEO services have helped my business improve its online presence and increase traffic to our website. He is knowledgeable, professional, and provides excellent results. I highly recommend him for all your SEO needs.",
        img: "emily-davis.png",
        logo: "logo-small-05.svg",
    },
    {
        id: 3,
        name: "David Kim",
        company: "Design Inc.",
        title: "Expert Webflow and SEO Services: Excellent Work, Great Results.",
        desc: "Working with Arik on my website redesign was a fantastic experience. He was able to take my vision and turn it into a beautiful and functional website. His attention to detail and creative approach is unmatched. I couldn't be happier with the end result.",
        img: "david-kim.png",
        logo: "logo-small-02.svg",
    },
    {
        id: 4,
        name: "Andrew Thompson",
        company: "Silverstone Corporation",
        title: "Expertise in Web Design: Second to None with Arik.",
        desc: "Arik is not only an exceptional web designer, but also a pleasure to work with. He took the time to understand my business and its unique needs, and created a website that perfectly represents my brand. I highly recommend Arik's services to anyone looking for a top-quality web designer.",
        img: "andrew-thompson.png",
        logo: "logo-small-04.svg",
    },
    {
        id: 5,
        name: "Ryan Chen",
        company: "Golden Gate Solutions",
        title: "High-Quality Web Design: Exceptional Attention to Detail with Arik.",
        desc: "Arik's development services are top-notch. He is able to take complex ideas and turn them into functional, user-friendly websites. His attention to detail and commitment to customer satisfaction are unmatched. I highly recommend Arik for all your web development needs.",
        img: "ryan-chen.png",
        logo: "logo-small-06.svg",
    },
];